services:
  db:
    image: postgres:16
    container_name: finance-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  jenkins:
    image: jenkins/jenkins:lts-jdk21
    container_name: finance-jenkins
    restart: always
    ports:
      - "8081:8080" # Port 8081 avoids collision with Spring Boot on 8080
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home

volumes:
  postgres_data:
  jenkins_data: